[package]
name = "algebra"
version = "0.1.0"
authors = ["Brendan Zabarauskas", "Darin Morrison"]
description = "Abstract algebra for Rust"
keywords = ["algebra", "monoids", "math"]
readme = "README.md"
repository = "https://github.com/bjz/algebra"

[lib]
name = "algebra"

# [dev_dependencies.quickcheck]
# git = "https://github.com/BurntSushi/quickcheck"
#
# [dev_dependencies.quickcheck_macros]
# git = "https://github.com/BurntSushi/quickcheck"
