[package]
name = "num"
version = "0.1.0"
authors = ["Brendan Zabarauskas"]

[lib]
name = "math"

[dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"
