[package]
name        = "alga_derive"
version     = "0.5.1"
authors     = ["Brendan Zabarauskas", "Darin Morrison", "SÃ©bastien Crozet"]
description = "Derive attribute for implementing algebraic traits from the alga crate."
keywords    = ["algebra", "monoids", "math"]
categories  = ["Science"]
readme      = "alga_derive/README.md"
repository  = "https://github.com/sebcrozet/alga"
license     = "Apache-2.0"

[lib]
name       = "alga_derive"
proc-macro = true

[dependencies]
quote         = "0.3"
syn           = "0.11"
edit-distance = "1.0"
quickcheck    = "0.3"
